#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-01-22 16:12:54.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("get_section_names_for_input() works", {

  swmmr:::get_section_names_for_input()

})

