#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-01-10 23:01:34.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("create_sf_of_pt() works", {

  expect_error(
    swmmr:::create_sf_of_pt()
    # argument "x" is missing, with no default
  )

})

