#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-01-10 23:01:36.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("input_to_list_of_sections() works", {

  expect_error(
    swmmr:::input_to_list_of_sections()
    # argument "path_options" is missing, with no default
  )

})

