#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-01-22 16:13:09.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("warn_formatted() works", {

  expect_error(
    swmmr:::warn_formatted()
    # argument "fmt" is missing, with no default
  )

})

