#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-01-10 23:01:35.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("timeseries_to_dat() works", {

  expect_error(
    swmmr:::timeseries_to_dat()
    # argument "x" is missing, with no default
  )

})

