#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-01-10 23:01:36.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("list_of_sections_to_inp() works", {

  expect_error(
    swmmr:::list_of_sections_to_inp()
    # argument "list_of_sections" is missing, with no default
  )

})

