#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-01-10 23:01:35.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("compare_to_dictionary() works", {

  f <- swmmr:::compare_to_dictionary
  
  expect_silent(f())

})
