#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-01-10 23:02:10.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("write_inp() works", {

  expect_error(
    swmmr:::write_inp()
    # argument "x" is missing, with no default
  )

})

