#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-01-10 23:01:58.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("run_swmm() works", {

  expect_error(
    swmmr:::run_swmm()
    # argument "inp" is missing, with no default
  )

})

