// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// get_eventpoints
arma::mat get_eventpoints(arma::vec xts, double threshold, int window);
RcppExport SEXP swmmr_get_eventpoints(SEXP xtsSEXP, SEXP thresholdSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type xts(xtsSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    __result = Rcpp::wrap(get_eventpoints(xts, threshold, window));
    return __result;
END_RCPP
}
// OpenSwmmOutFile
List OpenSwmmOutFile(const char* outFile);
RcppExport SEXP swmmr_OpenSwmmOutFile(SEXP outFileSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const char* >::type outFile(outFileSEXP);
    __result = Rcpp::wrap(OpenSwmmOutFile(outFile));
    return __result;
END_RCPP
}
// GetSwmmResult
Rcpp::NumericVector GetSwmmResult(int iType, int iIndex, int vIndex);
RcppExport SEXP swmmr_GetSwmmResult(SEXP iTypeSEXP, SEXP iIndexSEXP, SEXP vIndexSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type iType(iTypeSEXP);
    Rcpp::traits::input_parameter< int >::type iIndex(iIndexSEXP);
    Rcpp::traits::input_parameter< int >::type vIndex(vIndexSEXP);
    __result = Rcpp::wrap(GetSwmmResult(iType, iIndex, vIndex));
    return __result;
END_RCPP
}
// GetSwmmTimes
Rcpp::NumericVector GetSwmmTimes();
RcppExport SEXP swmmr_GetSwmmTimes() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(GetSwmmTimes());
    return __result;
END_RCPP
}
// CloseSwmmOutFile
int CloseSwmmOutFile();
RcppExport SEXP swmmr_CloseSwmmOutFile() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(CloseSwmmOutFile());
    return __result;
END_RCPP
}
