// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// OpenSwmmOutFile
List OpenSwmmOutFile(const char* outFile);
RcppExport SEXP _swmmr_OpenSwmmOutFile(SEXP outFileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char* >::type outFile(outFileSEXP);
    rcpp_result_gen = Rcpp::wrap(OpenSwmmOutFile(outFile));
    return rcpp_result_gen;
END_RCPP
}
// GetSwmmResult
Rcpp::NumericVector GetSwmmResult(int iType, int iIndex, int vIndex);
RcppExport SEXP _swmmr_GetSwmmResult(SEXP iTypeSEXP, SEXP iIndexSEXP, SEXP vIndexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type iType(iTypeSEXP);
    Rcpp::traits::input_parameter< int >::type iIndex(iIndexSEXP);
    Rcpp::traits::input_parameter< int >::type vIndex(vIndexSEXP);
    rcpp_result_gen = Rcpp::wrap(GetSwmmResult(iType, iIndex, vIndex));
    return rcpp_result_gen;
END_RCPP
}
// GetSwmmTimes
Rcpp::NumericVector GetSwmmTimes();
RcppExport SEXP _swmmr_GetSwmmTimes() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(GetSwmmTimes());
    return rcpp_result_gen;
END_RCPP
}
// CloseSwmmOutFile
int CloseSwmmOutFile();
RcppExport SEXP _swmmr_CloseSwmmOutFile() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(CloseSwmmOutFile());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_swmmr_OpenSwmmOutFile", (DL_FUNC) &_swmmr_OpenSwmmOutFile, 1},
    {"_swmmr_GetSwmmResult", (DL_FUNC) &_swmmr_GetSwmmResult, 3},
    {"_swmmr_GetSwmmTimes", (DL_FUNC) &_swmmr_GetSwmmTimes, 0},
    {"_swmmr_CloseSwmmOutFile", (DL_FUNC) &_swmmr_CloseSwmmOutFile, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_swmmr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
